export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';

export const API_CALL_SAMPLE_REQUEST = 'API_CALL_SAMPLE_REQUEST';
export const API_CALL_SAMPLE_SUCCESS = 'API_CALL_SAMPLE_SUCCESS';
export const API_CALL_SAMPLE_FAILURE = 'API_CALL_SAMPLE_FAILURE';

export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';
